config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "collections#index"

  resources :collections
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :confirmable, :database_authenticatable, :lockable, :registerable,
         :recoverable, :rememberable, :timeoutable, :trackable, :validatable

  has_many :collections, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticatable
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection.where(user_id: current_user.id)
  end

  def show
    @collection = current_user.collections.find(params[:id])
  end
end

app/controllers/concerns/authenticatable.rb
module Authenticatable 
  extend ActiveSupport::Concern

  included do
    prepend_before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collections/index.html.erb
<div>

  <h2>Collections Index</h2>

  <div>
    <% @collections.each do |collection| %>
      <div class="row">
        <div class="col">
          <%= collection.name %>
        </div>
        <div class="col">
          <%= link_to "Show", collection %>
        </div>
        <div class="col">
          <%= link_to "Edit", edit_collection_path(collection) %>
        </div>
        <div class="col">
          <%= link_to "Delete", collection, method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/collections/show.html.erb
<h2><%= @collection.name %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GearCloset</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>